language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-drywall-crud-app' ]; then cd .. && eval "mv $currentfolder generator-drywall-crud-app" && cd generator-drywall-crud-app; fi

